import { Item, Transaction } from './types';

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item-1',
    name: 'Kertas HVS A4 Sinar Dunia 80gr',
    category: 'Alat Tulis Kantor',
    unit: 'Rim',
    initialStock: 20,
    classification: 'consumable',
  },
  {
    id: 'item-2',
    name: 'Pulpen Kenko Gel Black 0.5mm',
    category: 'Alat Tulis Kantor',
    unit: 'Lusin',
    initialStock: 5,
    classification: 'consumable',
  },
  {
    id: 'item-3',
    name: 'Kopi Kapal Api Mix (Isi 10)',
    category: 'Pantry',
    unit: 'Pack',
    initialStock: 15,
    classification: 'consumable',
  },
  {
    id: 'item-4',
    name: 'Teh Celup Sariwangi (Isi 50)',
    category: 'Pantry',
    unit: 'Kotak',
    initialStock: 10,
    classification: 'consumable',
  },
  {
    id: 'item-5',
    name: 'Gula Pasir Gulaku Premium 1kg',
    category: 'Pantry',
    unit: 'Kg',
    initialStock: 8,
    classification: 'consumable',
  },
  {
    id: 'item-6',
    name: 'Tisu Wajah Paseo 250 Sheets',
    category: 'Kebersihan',
    unit: 'Pack',
    initialStock: 30,
    classification: 'consumable',
  },
  {
    id: 'item-7',
    name: 'Cairan Cuci Piring Mama Lemon 750ml',
    category: 'Kebersihan',
    unit: 'Pouch',
    initialStock: 6,
    classification: 'consumable',
  },
  {
    id: 'item-8',
    name: 'Sabun Cuci Tangan Yuri 375ml',
    category: 'Kebersihan',
    unit: 'Botol',
    initialStock: 12,
    classification: 'consumable',
  },
  {
    id: 'item-9',
    name: 'Kursi Kerja Ergonomis Jati',
    category: 'Fasilitas & Listrik',
    unit: 'Unit',
    initialStock: 15,
    classification: 'asset',
  },
  {
    id: 'item-10',
    name: 'Printer Epson L3210 WiFi',
    category: 'Fasilitas & Listrik',
    unit: 'Unit',
    initialStock: 2,
    classification: 'asset',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Mei 2026
  {
    id: 'tx-1',
    itemId: 'item-1',
    type: 'out',
    quantity: 5,
    date: '2026-05-12',
    notes: 'Kebutuhan cetak laporan bulanan Divisi Keuangan',
    pic: 'Rudi (Finance)',
  },
  {
    id: 'tx-2',
    itemId: 'item-3',
    type: 'out',
    quantity: 4,
    date: '2026-05-15',
    notes: 'Kebutuhan pantry ruang rapat utama',
    pic: 'Santi (HR)',
  },
  {
    id: 'tx-3',
    itemId: 'item-6',
    type: 'out',
    quantity: 10,
    date: '2026-05-18',
    notes: 'Distribusi tisu ke seluruh meja kerja staff',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-4',
    itemId: 'item-1',
    type: 'in',
    quantity: 15,
    date: '2026-05-20',
    notes: 'Restock bulanan dari Supplier ATK Utama',
    pic: 'Anto (Purchasing)',
  },
  // Juni 2026
  {
    id: 'tx-5',
    itemId: 'item-1',
    type: 'out',
    quantity: 8,
    date: '2026-06-05',
    notes: 'Kebutuhan cetak draft berkas tender',
    pic: 'Hendra (Project)',
  },
  {
    id: 'tx-6',
    itemId: 'item-2',
    type: 'out',
    quantity: 2,
    date: '2026-06-08',
    notes: 'Pembagian pulpen bulanan staff admin',
    pic: 'Santi (HR)',
  },
  {
    id: 'tx-7',
    itemId: 'item-3',
    type: 'out',
    quantity: 6,
    date: '2026-06-12',
    notes: 'Konsumsi rutin pantry staff',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-8',
    itemId: 'item-5',
    type: 'out',
    quantity: 3,
    date: '2026-06-15',
    notes: 'Kebutuhan pantry & dapur kantor',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-9',
    itemId: 'item-6',
    type: 'out',
    quantity: 12,
    date: '2026-06-20',
    notes: 'Stok tisu toilet & wastafel bulanan',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-10',
    itemId: 'item-4',
    type: 'out',
    quantity: 4,
    date: '2026-06-22',
    notes: 'Stok pantry teh celup',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-11',
    itemId: 'item-8',
    type: 'out',
    quantity: 4,
    date: '2026-06-25',
    notes: 'Isi ulang botol sabun cuci tangan toilet',
    pic: 'Budi (GA)',
  },
  // Juli 2026 (Bulan berjalan)
  {
    id: 'tx-12',
    itemId: 'item-1',
    type: 'out',
    quantity: 6,
    date: '2026-07-02',
    notes: 'Kebutuhan berkas audit internal',
    pic: 'Rudi (Finance)',
  },
  {
    id: 'tx-13',
    itemId: 'item-3',
    type: 'out',
    quantity: 3,
    date: '2026-07-05',
    notes: 'Penggunaan pantry harian',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-14',
    itemId: 'item-7',
    type: 'out',
    quantity: 2,
    date: '2026-07-08',
    notes: 'Penggunaan sabun Mama Lemon di dapur pantry',
    pic: 'Budi (GA)',
  },
  {
    id: 'tx-15',
    itemId: 'item-2',
    type: 'in',
    quantity: 10,
    date: '2026-07-10',
    notes: 'Pembelian pulpen tambahan via Petty Cash',
    pic: 'Anto (Purchasing)',
  },
];
